// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.3
// source: cookies/cookies.proto

package cookies

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cookie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flavor string `protobuf:"bytes,1,opt,name=flavor,proto3" json:"flavor,omitempty"`
}

func (x *Cookie) Reset() {
	*x = Cookie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cookies_cookies_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookie) ProtoMessage() {}

func (x *Cookie) ProtoReflect() protoreflect.Message {
	mi := &file_cookies_cookies_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookie.ProtoReflect.Descriptor instead.
func (*Cookie) Descriptor() ([]byte, []int) {
	return file_cookies_cookies_proto_rawDescGZIP(), []int{0}
}

func (x *Cookie) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

var File_cookies_cookies_proto protoreflect.FileDescriptor

var file_cookies_cookies_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73,
	0x22, 0x20, 0x0a, 0x06, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6c,
	0x61, 0x76, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6c, 0x61, 0x76,
	0x6f, 0x72, 0x32, 0x40, 0x0a, 0x0e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6f, 0x6b,
	0x69, 0x65, 0x12, 0x0f, 0x2e, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x1a, 0x0f, 0x2e, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x6f,
	0x6f, 0x6b, 0x69, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x64, 0x69, 0x74, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6f, 0x6b, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cookies_cookies_proto_rawDescOnce sync.Once
	file_cookies_cookies_proto_rawDescData = file_cookies_cookies_proto_rawDesc
)

func file_cookies_cookies_proto_rawDescGZIP() []byte {
	file_cookies_cookies_proto_rawDescOnce.Do(func() {
		file_cookies_cookies_proto_rawDescData = protoimpl.X.CompressGZIP(file_cookies_cookies_proto_rawDescData)
	})
	return file_cookies_cookies_proto_rawDescData
}

var file_cookies_cookies_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cookies_cookies_proto_goTypes = []interface{}{
	(*Cookie)(nil), // 0: cookies.Cookie
}
var file_cookies_cookies_proto_depIdxs = []int32{
	0, // 0: cookies.CookieTraveler.SendCookie:input_type -> cookies.Cookie
	0, // 1: cookies.CookieTraveler.SendCookie:output_type -> cookies.Cookie
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cookies_cookies_proto_init() }
func file_cookies_cookies_proto_init() {
	if File_cookies_cookies_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cookies_cookies_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cookie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cookies_cookies_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cookies_cookies_proto_goTypes,
		DependencyIndexes: file_cookies_cookies_proto_depIdxs,
		MessageInfos:      file_cookies_cookies_proto_msgTypes,
	}.Build()
	File_cookies_cookies_proto = out.File
	file_cookies_cookies_proto_rawDesc = nil
	file_cookies_cookies_proto_goTypes = nil
	file_cookies_cookies_proto_depIdxs = nil
}
